### ISSUE TITLE
Run failing on mac: no main class detected

### ISSUE THREAD

**Issue by deregs** [benthecarman/ln-vortex#41]
After following the setup process on mac, `sbt gui/run` is failing:

```
[error] java.lang.RuntimeException: No main class detected.
[error] 	at scala.sys.package$.error(package.scala:30)
```

However, `sbt gui/compile` succeeds.

Should `mainClass` be defined in the build file to resolve this?

**Comment by benthecarman** [comment]
Yeah, there is no gui currently built

**Comment by deregs** [comment]
Oh yeah my bad. I can help build the frontend if you're looking for help.
